version: "3.9"

services:
  backend:
    build: Dockerfile.dev
    container_name: backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend_api.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2 --timeout 120"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
