FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies for psycopg2 & Pillow
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . /app/

## LEGACY # Collect static files (optional if using S3 for static)
## LEGACY # RUN python manage.py collectstatic --noinput
# Collect static files
RUN python manage.py collectstatic --noinput

EXPOSE 8000

# Default command (overridable in docker-compose/ECS)
CMD ["gunicorn", "backend_api.wsgi:application", "--bind", "0.0.0.0:8000", "--workers=4", "--threads=2", "--timeout=120"]
