# Generated by Django 5.2.5 on 2025-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRIOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_if', models.CharField(max_length=64, unique=True)),
                ('securitizadora', models.CharField(blank=True, default='', max_length=255)),
                ('operacao', models.CharField(blank=True, default='', max_length=255)),
                ('classe_titulo', models.CharField(blank=True, default='', max_length=255)),
                ('emissao', models.CharField(blank=True, default='', max_length=255)),
                ('serie', models.CharField(blank=True, default='', max_length=255)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('montante_emitido', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('remuneracao', models.CharField(blank=True, default='', max_length=255)),
                ('spread_aa', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('prazo_meses', models.IntegerField(blank=True, null=True)),
                ('ativo_lastro', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_devedor', models.CharField(blank=True, default='', max_length=255)),
                ('agente_fiduciario', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_oferta', models.CharField(blank=True, default='', max_length=255)),
                ('regime_fiduciario', models.CharField(blank=True, default='', max_length=255)),
                ('pulverizado', models.BooleanField(blank=True, null=True)),
                ('qtd_emitida', models.IntegerField(blank=True, null=True)),
                ('segmento_imobiliario', models.CharField(blank=True, default='', max_length=255)),
                ('certificacao_esg', models.BooleanField(blank=True, null=True)),
                ('agencia_certificadora_esg', models.CharField(blank=True, default='', max_length=255)),
                ('contrato_lastro', models.CharField(blank=True, default='', max_length=255)),
                ('isin', models.CharField(blank=True, default='', max_length=64)),
                ('cedentes', models.CharField(blank=True, default='', max_length=255)),
                ('lider_distribuicao', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
