# Generated by Django 5.2.5 on 2025-08-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_tabela', models.DateField()),
                ('dias_uteis', models.PositiveIntegerField()),
                ('taxa_real', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('taxa_nominal', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('inflacao_implicita', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('composite_key', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
            options={
                'ordering': ('-data_da_tabela', 'dias_uteis'),
                'unique_together': {('data_da_tabela', 'dias_uteis')},
            },
        ),
    ]
