# Generated by Django 5.2.5 on 2025-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='crioperacao',
            name='carencia_juros_meses',
            field=models.CharField(default='N', help_text='Carência dos juros (ex.: N = não aplicável).'),
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='carencia_principal_meses',
            field=models.IntegerField(default=0, help_text='Período de carência em meses (0 = sem carência).'),
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='frequencia_juros',
            field=models.CharField(default='M', help_text='Frequência de pagamento dos juros.', max_length=30),
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='frequencia_principal',
            field=models.CharField(default='M', help_text='Frequência de amortização do principal.', max_length=30),
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='tabela_juros',
            field=models.CharField(default='Integral', help_text='Tabela de juros (ex.: Integral).', max_length=30),
        ),
    ]
