# Generated by Django 5.2.4 on 2025-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crioperacao_carencia_juros_meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crioperacao',
            name='agencia_certificadora_esg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='agente_fiduciario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='ativo_lastro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='carencia_juros_meses',
            field=models.CharField(blank=True, help_text='Carência dos juros (ex.: N = não aplicável).', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='carencia_principal_meses',
            field=models.IntegerField(blank=True, help_text='Período de carência em meses (0 = sem carência).', null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='cedentes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='classe_titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='contrato_lastro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='emissao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='frequencia_juros',
            field=models.CharField(blank=True, help_text='Frequência de pagamento dos juros.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='frequencia_principal',
            field=models.CharField(blank=True, help_text='Frequência de amortização do principal.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='isin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='lider_distribuicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='operacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='regime_fiduciario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='remuneracao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='securitizadora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='segmento_imobiliario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='serie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='tabela_juros',
            field=models.CharField(blank=True, help_text='Tabela de juros (ex.: Integral).', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='tipo_devedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crioperacao',
            name='tipo_oferta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
