# Generated by Django 5.2.4 on 2025-08-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_crioperacao_agencia_certificadora_esg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=64)),
                ('codigo_if', models.CharField(max_length=64)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=32, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('isin', 'codigo_if', 'cpf_cnpj')},
            },
        ),
    ]
