# Generated by Django 5.2.4 on 2025-08-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_investidor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investidor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='investidor',
            name='classe_investida',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='investidor',
            name='fii_investidor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investidor',
            name='mes_referencia',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='investidor',
            name='nome_operacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investidor',
            name='serie_investida',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='investidor',
            name='valor_mercado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.RemoveField(
            model_name='investidor',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='investidor',
            name='nome',
        ),
    ]
