# Generated by Django 5.2.4 on 2025-08-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_investidor_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investidor',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='investidor',
            name='classe_investida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investidor',
            name='codigo_if',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='investidor',
            name='isin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='investidor',
            name='mes_referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investidor',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='investidor',
            name='serie_investida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investidor',
            name='valor_mercado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
