# Generated by Django 5.2.4 on 2025-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_investidor_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investidor',
            name='codigo_if',
            field=models.CharField(max_length=50),
        ),
    ]
