# Generated by Django 5.2.4 on 2025-09-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_investidor_codigo_if'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCADiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('variacao_pct', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
