# Generated by Django 5.2.4 on 2025-09-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ipcadiario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipcadiario',
            old_name='valor',
            new_name='index',
        ),
    ]
