# Generated by Django 5.2.4 on 2025-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_valor_ipcadiario_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('preco_minimo', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('preco_maximo', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('preco_ultimo', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('quantidade', models.BigIntegerField(blank=True, null=True)),
                ('num_negocios', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ambiente', models.CharField(max_length=50)),
            ],
        ),
    ]
