# Generated by Django 5.2.4 on 2025-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='preco',
            name='codigo_if',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preco',
            name='isin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='preco',
            unique_together={('isin', 'codigo_if', 'data')},
        ),
    ]
