# Generated by Django 5.2.4 on 2025-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_preco_codigo_if_preco_isin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='ambiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preco',
            name='classe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
