# Generated by Django 5.2.4 on 2025-09-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_preco_ambiente_alter_preco_classe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preco',
            options={'ordering': ['-data']},
        ),
        migrations.AlterUniqueTogether(
            name='preco',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='preco',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
