# Generated by Django 5.2.4 on 2025-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_preco_options_alter_preco_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
