# Generated by Django 5.2.4 on 2025-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_preco_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crioperacao',
            name='carencia_juros_meses',
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='frequencia_integralizacao',
            field=models.CharField(blank=True, help_text='Frequência de integralização.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='metodo_principal',
            field=models.CharField(blank=True, help_text='Método de amortização do principal.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='periodo_integralizacao',
            field=models.CharField(blank=True, help_text='Período de integralização.', max_length=30, null=True),
        ),
    ]
