# Generated by Django 5.2.4 on 2025-09-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_crioperacao_carencia_juros_meses_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investidor',
            unique_together={('isin', 'codigo_if', 'fii_investidor', 'mes_referencia')},
        ),
    ]
