# Generated by Django 5.2.4 on 2025-09-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_investidor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investidor',
            unique_together=set(),
        ),
    ]
