# Generated by Django 5.2.4 on 2025-09-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_preco_duration_preco_spread_preco_taxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='crioperacao',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='spread',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='crioperacao',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
